name: Deploy via Azure RunCommand
on: { push: { branches: [ main ] } }

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy on VM (as user)
        uses: azure/cli@v2
        with:
          inlineScript: |
            az vm run-command invoke \
              --resource-group "${{ secrets.AZ_RG }}" \
              --name "${{ secrets.AZ_VM }}" \
              --command-id RunShellScript \
              --scripts '
                set -euo pipefail

                # root: ensure system deps
                command -v node >/dev/null || (curl -fsSL https://deb.nodesource.com/setup_22.x | sudo -E bash - && sudo apt -y install nodejs build-essential)
                sudo npm i -g yarn pm2

                # run as the login user
                sudo -u aum-sitrai bash -lc "
                  set -euo pipefail
                  APP_DIR=\$HOME/aum-ai
                  REPO_URL=https://github.com/sumanrajsah/aum-ai.git
                  TOKEN=${{ secrets.GH_PAT }}

                  mkdir -p \$APP_DIR
                  cd \$APP_DIR

                  # first-time clone with PAT header
                  if [ ! -d .git ]; then
                    git -c http.extraHeader=\"Authorization: Bearer \$TOKEN\" clone \$REPO_URL .
                  fi

                  # fetch/reset with PAT header
                  git -c http.extraHeader=\"Authorization: Bearer \$TOKEN\" fetch --all
                  git -c http.extraHeader=\"Authorization: Bearer \$TOKEN\" reset --hard origin/main

                  cat > .env.production <<EOF
                  NEXT_PUBLIC_API_URI=${{ secrets.NEXT_PUBLIC_API_URI }}
                  NEXT_PUBLIC_GOOGLE_CLIENT_ID=${{ secrets.NEXT_PUBLIC_GOOGLE_CLIENT_ID }}
                  EOF

                  yarn install --frozen-lockfile
                  yarn build

                  pm2 describe aum-ai >/dev/null && pm2 reload aum-ai || pm2 start node_modules/next/dist/bin/next --name aum-ai -- start
                  pm2 save
                "
              '
