name: Deploy via Azure RunCommand
on: { push: { branches: [ main ] } }

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy on VM (as user)
        uses: azure/cli@v2
        with:
          azcliversion: 2.30.0
          inlineScript: |
            az vm run-command invoke \
              --resource-group "${{ secrets.AZ_RG }}" \
              --name "${{ secrets.AZ_VM }}" \
              --command-id RunShellScript \
              --scripts "$(cat << 'DEPLOY_SCRIPT'
            #!/bin/bash
            
            # Simple error handling without complex trapping
            set -e
            
            echo "=== Deployment started at $(date) ==="
            
            # System dependencies
            echo "=== Installing system dependencies ==="
            if ! command -v node >/dev/null 2>&1; then
              echo "Installing Node.js..."
              curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
              sudo apt-get update
              sudo apt-get install -y nodejs build-essential git python3
            else
              echo "Node.js already installed: $(node -v)"
            fi
            
            # Install global packages
            echo "=== Installing global packages ==="
            sudo npm install -g pm2@latest corepack
            
            # Create user if not exists
            if ! id aum-sitrai >/dev/null 2>&1; then
              sudo useradd -m -s /bin/bash aum-sitrai
              echo "Created user aum-sitrai"
            fi
            
            # Run as user
            echo "=== Starting deployment as user ==="
            sudo -H -u aum-sitrai bash << 'USER_SCRIPT'
            set -e
            export HOME=/home/aum-sitrai
            export PATH="/usr/local/bin:/usr/bin:/bin:$HOME/.local/bin:$PATH"
            cd $HOME
            
            echo "User: $(whoami)"
            echo "Home: $HOME"
            echo "Node version: $(node -v)"
            echo "npm version: $(npm -v)"
            
            # Setup app directory
            APP_DIR="$HOME/aum-ai"
            REPO_URL="https://token:${{ secrets.GH_PAT }}@github.com/sumanrajsah/aum-ai.git"
            
            echo "=== Repository setup ==="
            if [ -d "$APP_DIR" ]; then
              echo "Updating existing repository..."
              cd "$APP_DIR"
              git remote set-url origin "$REPO_URL"
              git fetch --all
              git reset --hard origin/main
              git clean -fd
            else
              echo "Cloning repository..."
              git clone "$REPO_URL" "$APP_DIR"
              cd "$APP_DIR"
            fi
            
            # Create environment file
            echo "=== Creating environment file ==="
            cat > .env.local << ENV_FILE
            NEXT_PUBLIC_API_URI=${{ secrets.NEXT_PUBLIC_API_URI }}
            NEXT_PUBLIC_GOOGLE_CLIENT_ID=${{ secrets.NEXT_PUBLIC_GOOGLE_CLIENT_ID }}
            NODE_ENV=production
            ENV_FILE
            
            # Setup Yarn
            echo "=== Setting up Yarn ==="
            corepack enable
            corepack prepare yarn@stable --activate
            
            if ! command -v yarn >/dev/null 2>&1; then
              echo "ERROR: Yarn not available"
              exit 1
            fi
            echo "Yarn version: $(yarn -v)"
            
            # Install dependencies
            echo "=== Installing dependencies ==="
            yarn cache clean || true
            rm -rf node_modules || true
            yarn install --frozen-lockfile --network-timeout 300000
            
            # Build application
            echo "=== Building application ==="
            export NODE_OPTIONS="--max-old-space-size=2048"
            yarn build
            
            # PM2 setup
            echo "=== PM2 setup ==="
            export PM2_HOME="$HOME/.pm2"
            
            if pm2 describe aum-ai >/dev/null 2>&1; then
              echo "Reloading existing PM2 process..."
              pm2 reload aum-ai
            else
              echo "Starting new PM2 process..."
              pm2 start npm --name aum-ai -- start
            fi
            
            pm2 save
            
            echo "=== Deployment completed at $(date) ==="
            pm2 status
            USER_SCRIPT
            
            echo "=== Overall deployment completed successfully ==="
            DEPLOY_SCRIPT
            )"

      - name: Verify deployment
        uses: azure/cli@v2
        with:
          azcliversion: 2.30.0
          inlineScript: |
            echo "=== Checking deployment status ==="
            az vm run-command invoke \
              --resource-group "${{ secrets.AZ_RG }}" \
              --name "${{ secrets.AZ_VM }}" \
              --command-id RunShellScript \
              --scripts "
                echo '=== PM2 Status ==='
                sudo -u aum-sitrai pm2 status || echo 'PM2 status check failed'
                echo '=== PM2 Logs (last 10 lines) ==='
                sudo -u aum-sitrai pm2 logs aum-ai --lines 10 --nostream || echo 'PM2 logs not available'
                echo '=== Process Check ==='
                ps aux | grep node || echo 'No node processes found'
              "