name: Deploy via Azure RunCommand
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { persist-credentials: false }

      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy on VM (as user)
        uses: azure/cli@v2
        with:
          inlineScript: |
            az vm run-command invoke \
              --resource-group "${{ secrets.AZ_RG }}" \
              --name "${{ secrets.AZ_VM }}" \
              --command-id RunShellScript \
              --scripts '
                # run everything under bash via heredoc
                bash <<'"'"'BASH'"'"'
                set -Eeuo pipefail
                trap '"'"'rc=$?; echo "[ERR] line:$LINENO cmd:${BASH_COMMAND} status:$rc" >&2; exit $rc'"'"' ERR

                # tracing
                PS4="+ [TRACE] "
                exec > >(tee -a /home/aum-sitrai/deploy.log) 2>&1
                set -x

                # sys deps
                sudo apt-get update -y
                sudo apt-get install -y curl ca-certificates gnupg git build-essential python3
                if ! command -v node >/dev/null 2>&1; then
                  curl -fsSL https://deb.nodesource.com/setup_22.x | sudo -E bash -
                  sudo apt-get install -y nodejs
                fi
                sudo npm i -g pm2 corepack

                # ensure user
                id aum-sitrai >/dev/null 2>&1 || sudo useradd -m -s /bin/bash aum-sitrai

                # app as user
                sudo -iu aum-sitrai bash -lc "
                  set -Eeuo pipefail
                  trap 'rc=\$?; echo \"[USER ERR] line:\$LINENO cmd:\$BASH_COMMAND status:\$rc\" >&2; exit \$rc' ERR
                  PS4='+ [USER TRACE] '
                  set -x

                  APP_DIR=\$HOME/aum-ai
                  REPO_URL=https://token:${{ secrets.GH_PAT }}@github.com/sumanrajsah/aum-ai.git

                  mkdir -p \"\$APP_DIR\"
                  if [ -d \"\$APP_DIR/.git\" ]; then
                    git -C \"\$APP_DIR\" remote set-url origin \"\$REPO_URL\"
                    git -C \"\$APP_DIR\" fetch --prune origin
                    git -C \"\$APP_DIR\" reset --hard origin/main
                    git -C \"\$APP_DIR\" clean -fd
                  else
                    git clone --depth=1 \"\$REPO_URL\" \"\$APP_DIR\"
                  fi
                  cd \"\$APP_DIR\"

                  # secrets: disable xtrace while writing
                  { set +x; } 2>/dev/null
                  umask 077
                  cat > .env.production <<EOF
                  NEXT_PUBLIC_API_URI=${{ secrets.NEXT_PUBLIC_API_URI }}
                  NEXT_PUBLIC_GOOGLE_CLIENT_ID=${{ secrets.NEXT_PUBLIC_GOOGLE_CLIENT_ID }}
                  NODE_ENV=production
                  EOF
                  set -x

                  corepack enable
                  corepack prepare yarn@stable --activate
                  yarn -v

                  yarn cache clean --all || true
                  rm -rf node_modules/.cache || true

                  for i in 1 2 3; do
                    echo \"[STEP] yarn install attempt \$i/3\"
                    if yarn install; then
                      echo \"[OK] deps installed\"
                      break
                    fi
                    echo \"[WARN] install failed, retrying...\"
                    rm -rf node_modules || true
                    sleep 10
                    [ \$i -eq 3 ] && { echo \"[FATAL] install failed\" >&2; exit 1; }
                  done

                  export NODE_OPTIONS=--max-old-space-size=2048
                  echo \"[STEP] yarn build\"
                  yarn build

                  export PM2_HOME=\$HOME/.pm2
                  if pm2 describe aum-ai >/dev/null 2>&1; then
                    pm2 reload aum-ai --update-env
                  else
                    pm2 start \"yarn start\" --name aum-ai
                  fi
                  pm2 save
                  pm2 status
                "
                BASH
              '
